
name: deploy branch metadata
on:
  push:
    branches:    
      - 'qa'                            
jobs:
  deploy-branch:
    runs-on: ubuntu-latest                     
    timeout-minutes: 30
    steps:
      - name: install Salesforce CLI     
        run: |
          wget -nv https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          echo "$GITHUB_WORKSPACE/sfdx-cli/bin" >> $GITHUB_PATH
      - name: check out repository code  
        uses: actions/checkout@v2
        with:   
          path: 'repo'
      - name: create ssh connection for ci repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SFDC_CI_DEPLOY_CODE }}
      - name: check out ci repo
        run: git clone git@github.com:purlos/sfdc-ci.git
      - name: remove certain metadata types from deployment
        run: ./sfdc-ci/sfdx/sfdx_metadata_removal.sh
      - name: run script to authenticate sfdx to STAGING_1124  # if the branch that has received a commit is STAGING_1124, then authenticate to the Staging org
        if: endsWith(github.ref, '/STAGING_1124')
        # run: ./sfdc-ci/sfdx/sfdx_authenticate.sh -r ./sfdc-ci -k ${{ secrets.SFDX_DECRYPTION_KEY }} -i ${{ secrets.SFDX_DECRYPTION_IV }} -p ${{ secrets.SFDC_URL_STAGING }} -c ${{ secrets.SFDX_CLIENTID_STAGING }} -u ${{ secrets.SFDX_USERNAME_STAGING }}
        run: ./sfdc-ci/sfdx/sfdx_authenticate.sh -r ./sfdc-ci -k ${{ secrets.URL_TO_DEPLOY }} -c ${{ secrets.CONSUMER_KEY }} -u ${{ secrets.USER_NAME }}

      # below an example of how this can be used for other branches
      #- name: run script to authenticate sfdx to CI 
      #  if: github.ref == 'CI'
      #  run: ./sfdc-ci/sfdx/sfdx_authenticate.sh -r ./sfdc-ci -k ${{ secrets.SFDX_DECRYPTION_KEY }} -i ${{ secrets.SFDX_DECRYPTION_IV }} -p ${{ secrets.SFDC_URL_CI }} -c ${{ secrets.SFDX_CLIENTID_CI }} -u ${{ secrets.SFDX_USERNAME_CI }}
      - name: deploy the metadata
        run: |
          cd repo
          sfdx force:source:deploy -u CI --verbose -w 60 -l NoTestRun -p force-app/main/default
      - name: logout of the Salesforce org 
        run: sfdx auth:logout --all --noprompt
